baseURL = "https://albert.garcia.gibert.es/"
languageCode = "es-es"
title = "Albert García Gibert"
paginate = 5
pluralizelisttitles = false
DisqusShortname = "albert-garcia-gibert"
canonifyurls = true
theme = "casper"
publishDir = "docs"
assetDir = "static"

[params]
  paginatedSections="post test"
  metaDescription = "Building CryptoAdvisor.Club, the easy and calm crypto investment bot. Cofounder and former CTO of Uvinum. Founder of Obolog and Splitweet. Father of Júlia & Abril. I'd like to travel more and improve my guitar skills."
  description = "Working at <a href='https://www.krakend.io/'>KrakenD</a>, the ultra-performant API Gateway, and <a href='https://cryptoadvisor.club'>CryptoAdvisor.Club</a>, the easy and calm crypto investment bot.<br>Cofounder and former CTO of <a href='https://www.lavanguardia.com/economia/emprendedores/20180804/451201682513/pernod-ricard-uvinum.html'>Uvinum</a>.<br>Prev. <a href='/despedida-cierre-obolog/'>Softonic</a>, <a href='/despedida-cierre-obolog/'>Obolog</a> and <a href='https://computerhoy.com/noticias/internet/hootsuite-compra-start-espanola-splitweet-2493'>Splitweet</a>.<br><br>Father of two. I'd like to travel more and improve my guitar skills."
  cover = "/images/background-202006041954.jpg"
  author = "Albert García Gibert"
  authorlocation = "El Prat de Llobregat, Barcelona"
  authorwebsite = "https://twitter.com/obokaman"
  authorbio= "Cofounder and former CTO of Uvinum. Founder of Obolog and Splitweet. Father of Júlia & Abril. I'd like to travel more and improve my guitar skills."
  authoravatar = "/images/avatar.jpg"
  logo = "favicon.ico"
  googleAnalyticsUserID = "UA-97247-14"
  githubName = "obokaman-com"
  twitterName = "obokaman"
  facebookName = "obokaman"
  linkedinName = "obokaman"
  youtubeName = "obokaman"
  instagramName = "obokaman"
  email = "albert.garcia@gibert.es"
  hideHUGOSupport = false
  hjsStyle = "default"

[permalinks]
  post = "/:slug/"

[params.social]
  twitter = "obokaman"
