baseURL = "https://albert.garcia.gibert.es/"
languageCode = "es-es"
title = "Albert García Gibert"
paginate = 5
pluralizelisttitles = false
DisqusShortname = "albert-garcia-gibert"
canonifyurls = true
theme = "casper"
publishDir = "docs"
assetDir = "static"

[params]
  paginatedSections="post test"
  description = "Cofounder and former CTO of Uvinum. Founder of Obolog and Splitweet. Father of Júlia & Abril. I'd like to travel more and improve my guitar skills."
  cover = "/images/background-202006041954.jpg"
  author = "Albert García Gibert"
  authorlocation = "El Prat de Llobregat, Barcelona"
  authorwebsite = "https://twitter.com/obokaman"
  authorbio= "Cofounder and former CTO of Uvinum. Founder of Obolog and Splitweet. Father of Júlia & Abril. I'd like to travel more and improve my guitar skills."
  authoravatar = "/images/avatar.jpg"
  logo = "favicon.ico"
  googleAnalyticsUserID = "UA-97247-14"
  githubName = "obokaman-com"
  twitterName = "obokaman"
  facebookName = "obokaman"
  linkedinName = "obokaman"
  flickrName = "obokaman"
  instagramName = "obokaman"
  email = "albert.garcia@gibert.es"
  hideHUGOSupport = false
  hjsStyle = "default"

[permalinks]
  post = "/:slug/"

[params.social]
  twitter = "obokaman"
