backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - label: "Blog"
    name: "blog"
    folder: "content/post"
    create: true
    fields:
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Tags", name: "body", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
